name: Azure Web App CI/CD

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from GitHub

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx to build multi-platform Docker images

    - name: Login to DockerHub
      uses: docker/login-action@v1  # Log in to DockerHub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend ./frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-backend

    - name: Login to Azure
      uses: azure/login@v1  # Log in to Azure using GitHub secrets
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        # Deploy React frontend to Azure Web App
        az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myReactApp --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/react-frontend
        # Deploy Flask backend to Azure Web App
        az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myFlaskApp --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/flask-backend
