name: Azure Web App CI/CD

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    environment: production  # Use the "production" environment created in GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your code from GitHub

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx to build multi-platform Docker images

    - name: Login to DockerHub
      uses: docker/login-action@v1  # Log in to DockerHub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker images
      run: |
        # Build and push the React frontend Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend
        
        # Build and push the Flask backend Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-backend

    - name: Login to Azure
      uses: azure/login@v1  # Log in to Azure using GitHub secrets
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App - React Frontend
      run: |
        # Deploy React frontend to Azure Web App (he-frontend)
        az webapp config container set --name he-frontend --resource-group HE-WebApp --docker-custom-image-name ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest

    - name: Deploy to Azure Web App - Flask Backend
      run: |
        # Deploy Flask backend to Azure Web App (HE-backend)
        az webapp config container set --name HE-backend --resource-group HE-WebApp --docker-custom-image-name ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
