name: Build and deploy Python app to Azure Web App - HE-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip backend code
        run: |
          cd backend
          zip -r ../release.zip . -x "venv/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Unzip for deploy
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_560493E05CA24631A392DB514214988D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B201FD3A17F6427B88FD2A09C2E3FC98 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69A9BF96E39345859EC56CE286E910DA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "HE-Backend"
          slot-name: "Production"
          package: .
