name: Deploy React App to Azure Web App - HE-Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_560493E05CA24631A392DB514214988D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B201FD3A17F6427B88FD2A09C2E3FC98 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69A9BF96E39345859EC56CE286E910DA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "HE-Frontend"
          slot-name: "Production"
          package: frontend/build
